<?php

namespace pocketmine\entity;

use pocketmine\item\Item as ItemItem;
use pocketmine\level\particle\GenericParticle;
use pocketmine\network\mcpe\protocol\LevelEventPacket;

class EnderSignal extends Entity{
	const NETWORK_ID = self::EYE_OF_ENDER_SIGNAL;

	public $width = 0;
	public $length = 0;
	public $height = 0;

	public function onUpdate(int $currentTick): bool{
		if ($this->closed){
			return false;
		}

		$this->timings->startTiming();

		$hasUpdate = parent::onUpdate($currentTick);

		if ($this->age > 50){
			$this->kill();
			$hasUpdate = true;
			$this->getLevel()->dropItem($this, ItemItem::get(ItemItem::ENDER_EYE), $this);
		}

		$this->timings->stopTiming();

		return $hasUpdate;
	}

	public function kill(){
		$this->getLevel()->addParticle(new GenericParticle($this, LevelEventPacket::EVENT_PARTICLE_EYE_DESPAWN));
		parent::kill(); // TODO: Change the autogenerated stub
	}

	public function getName(): string{
		return "Eye of Ender";
	}
}